### Guard::Konacha
#  available options:
#  - :spec_dir, defaults to 'spec/javascripts'
#  - :driver, defaults to :selenium
guard :konacha do
  watch(%r{^app/assets/javascripts/(.*)\.js(\.coffee)?$}) { |m| "#{m[1]}_spec.js" }
  watch(%r{^spec/javascripts/.+_spec(\.js|\.js\.coffee)$})
end
